name: Accessibility Check

on: [pull_request, push]

jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Node server
        run: |
          npm install
          node server.js &
          sleep 5 # Attendre que le serveur démarre

      - name: Install Pa11y
        run: npm install -g pa11y-ci

      - name: Run accessibility tests
        run: pa11y-ci --config pa11y-ci.json
